#!/usr/bin/env python3
"""Extract the firmware's default bank table into the simulator.

`default_bank_sysex_parameters` in firmware/src/main.cpp is the real factory
content of the 12 banks. The simulator embeds it so that bank switching and
the reset-to-defaults command behave like the device rather than like a guess
assembled from parameters.json defaults.

Regenerate after touching that table:
    python3 tools/extract-firmware-defaults.py
"""

from __future__ import annotations

import re
from pathlib import Path

PARAMETER_SIZE = 256
BANK_COUNT = 12

REPO_ROOT = Path(__file__).resolve().parents[3]
MAIN_CPP = REPO_ROOT / "firmware" / "src" / "main.cpp"
OUTPUT = Path(__file__).resolve().parents[1] / "src" / "dev" / "simulator" / "defaultBanks.ts"


def extract(source: str, symbol: str, rows: int) -> list[list[int]]:
    start = source.index(symbol)
    start = source.index("{", start)
    depth = 0
    for end, character in enumerate(source[start:], start):
        depth += (character == "{") - (character == "}")
        if depth == 0:
            break
    body = source[start + 1 : end]
    banks = [
        [int(n) for n in re.findall(r"-?\d+", row)]
        for row in re.findall(r"\{([^{}]*)\}", body)
    ]
    if len(banks) != rows or any(len(b) != PARAMETER_SIZE for b in banks):
        raise SystemExit(
            f"{symbol}: expected {rows}x{PARAMETER_SIZE}, got "
            f"{len(banks)}x{[len(b) for b in banks]}"
        )
    return banks


def main() -> None:
    source = MAIN_CPP.read_text()
    banks = extract(source, "default_bank_sysex_parameters", BANK_COUNT)

    lines = [
        "// Generated by tools/extract-firmware-defaults.py -- do not edit by hand.",
        "// Source: firmware/src/main.cpp, default_bank_sysex_parameters.",
        "//",
        "// The factory content of the 12 banks, exactly as the firmware ships it.",
        "",
        f"export const PARAMETER_SIZE = {PARAMETER_SIZE}",
        f"export const BANK_COUNT = {BANK_COUNT}",
        "",
        "export const DEFAULT_BANKS: readonly (readonly number[])[] = [",
    ]
    lines += [f"  [{', '.join(str(v) for v in bank)}]," for bank in banks]
    lines += ["]", ""]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({BANK_COUNT} banks)")


if __name__ == "__main__":
    main()
